  int x=1000,y=500;
 void setup() {
  // put your setup code here, to run once:
  pinMode(2,OUTPUT);
  pinMode(3,OUTPUT);
   pinMode(4,OUTPUT);
   pinMode(5,OUTPUT);
   pinMode(6,OUTPUT);
   pinMode(7,OUTPUT);
   pinMode(8,OUTPUT);
   pinMode(9,OUTPUT);

  
  digitalWrite(2, HIGH);
  delay(x);
  digitalWrite(2, LOW);
  delay(y);
   digitalWrite(3, HIGH);
  delay(x);
  digitalWrite(3, LOW);
  delay(y);
   digitalWrite(4, HIGH);
  delay(x);
  digitalWrite(4, LOW);
  delay(y);
   digitalWrite(5, HIGH);
  delay(x);
  digitalWrite(5, LOW);
  delay(y);
   digitalWrite(6, HIGH);
  delay(x);
  digitalWrite(6, LOW);
  delay(y);
   digitalWrite(7, HIGH);
  delay(x);
  digitalWrite(7, LOW);
  delay(y);
   digitalWrite(8, HIGH);
  delay(x);
  digitalWrite(8, LOW);
  delay(y);
   digitalWrite(9, HIGH);
  delay(x);
  digitalWrite(9, LOW);
  delay(y);
  }

void loop() {
 
 digitalWrite(2, HIGH);
  delay(x);
  digitalWrite(2, LOW);
  delay(y);
  digitalWrite(3, HIGH);
  delay(x);
  digitalWrite(3, LOW);
  delay(y);
   digitalWrite(4, HIGH);
  delay(x);
  digitalWrite(4, LOW);
  delay(y);
   digitalWrite(5, HIGH);
  delay(x);
  digitalWrite(5, LOW);
  delay(y);
   digitalWrite(6, HIGH);
  delay(x);
  digitalWrite(6, LOW);
  delay(y);
   digitalWrite(7, HIGH);
  delay(x);
  digitalWrite(7, LOW);
  delay(y);
   digitalWrite(8, HIGH);
  delay(x);
  digitalWrite(8, LOW);
  delay(y);
   digitalWrite(9, HIGH);
  delay(x);
  digitalWrite(9, LOW);
  delay(y);
  digitalWrite(9, HIGH);
  delay(x);
  digitalWrite(9, LOW);
  delay(y);
  digitalWrite(8, HIGH);
  delay(x);
  digitalWrite(8, LOW);
  delay(y);
   digitalWrite(7, HIGH);
  delay(x);
  digitalWrite(7, LOW);
  delay(y);
   digitalWrite(6, HIGH);
  delay(x);
  digitalWrite(6, LOW);
  delay(y);
   digitalWrite(5, HIGH);
  delay(x);
  digitalWrite(5, LOW);
  delay(y);
   digitalWrite(4, HIGH);
  delay(x);
  digitalWrite(4, LOW);
  delay(y);
   digitalWrite(3, HIGH);
  delay(x);
  digitalWrite(3, LOW);
  delay(y);
   digitalWrite(2, HIGH);
  delay(x);
  digitalWrite(2, LOW);
  delay(y);
}
